import Home from "./Home/Home"
import Error404 from "./Error404/Error404"
// import Profile from "./Profile/Profile"
import HotBluds from "./HotBluds/HotBluds"
import Deserts from "./Deserts/Deserts"
import Soups from "./Soups/Soups"
import Drinks from "./Drinks/Drinks"
import Salats from "./Salats/Salats"
import Oform from "./Oform/Oform"
import NewBeak from "./NewBeak/NewBeak"
import ColdSnacks from "./ColdSnacks/ColdSnacks"
import Backet from "./Backet/Backet"
import Xinkali from "./Xinkali/Xinkali"
import Kontaks from "./Kontaks/Kontaks"
import Soglashenie from "./Soglashenie/Soglashenie"
import Politika from "./Politika/Politika"

export{Error404, Home, HotBluds, Deserts, Soups, Salats, Drinks, NewBeak, ColdSnacks, Backet, Xinkali, Kontaks, Politika, Soglashenie,Oform}